name: generate results

on:
  push:
    branches: [ main ]


jobs:
  generate-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install jinja2 pandas pytz seaborn pint
      - run: python generate-results.py
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'Results.md *.png'
          author_name: ilastik-bot
          committer_name: ilastik bot
          message: '(bot) Updated results'
          new_branch: results
          push: 'origin results --force'
